### ISSUE TITLE
Develop historical crop patterns

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-data#20]
Although strictly not a part of the farm budget data, we need a list of the commodities in play over each CMZ zone for use in the SWAP model.  These are basically aggregations of the NASS input data.

**Comment by qjhart** [comment]
@blyeo / @judyhanna These are in the nass-summary directory.  Specifically, https://github.com/CSTARS/farm-budgets-data/blob/master/nass-summary-0.1-alpha/cmz_commodity_total_harvest.csv  which shows each commodity by irrigated and non-irrigated acres.  This is for census data starting from 1997.

It's actually *not \* easy to determine the irrigated and non-irrigated components, and these should be considered as approximate.

**Comment by blyeo** [comment]
Just to clarify--the whole purpose of having irrigated and non irrigated
land (disaggregated) is because we have different land rent value for
irrigated and non irrigated land, right? Are there any other
differentiation in costs for non-irrigated vs. irrigated lands that we need
to be aware of besides land rental rates?

**Comment by qjhart** [comment]
@blyeo And the cost of irrigation as well.  Other than that, I don't think I've ever seen a budget that differentiates between them.

**Comment by blyeo** [comment]
Got it!

Judy--have you found different irrigation costs for irrigated and
non-irrigated agricultural croplands?
